.PHONY: clean All

All:
	@echo "----------Building project:[ CEDA - Debug ]----------"
	@cd "CEDA" && "$(MAKE)" -f  "CEDA.mk"
clean:
	@echo "----------Cleaning project:[ CEDA - Debug ]----------"
	@cd "CEDA" && "$(MAKE)" -f  "CEDA.mk" clean
